name: AntiMicroX build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      - name: setup qemu
        run: |
          sudo apt update
          sudo apt install qemu-user curl bash -y
          wget -q https://github.com/Crilum/Github-Actions-App-Builds/blob/main/resources/bash?raw=true
      - name: run build in qemu-user
        run: |
          get_release() {
          curl --silent "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name' | sed s/v//g
          }
          validate_url(){
          if command wget -q --spider "$1"; then
          return 0
          else
          return 1
          fi
          }
          echo "Checking URLs..."
          validate_url "https://api.github.com/repos/AntiMicroX/antimicrox/releases/latest"
          if [ "$?" == "1" ]; then
          echo "Got a bad response from 'https://api.github.com/repos/AntiMicroX/antimicrox/releases/latest'"
          exit 1
          else
          validate_url "https://github.com/AntiMicroX/antimicrox"
          if [ "$?" == "1" ]; then
          echo "Got a bad response from 'https://github.com/AntiMicroX/antimicrox'"
          exit 1
          fi
          fi
          echo "Done."
          webVer=$(get_release AntiMicroX/antimicrox)
          sudo qemu-arm -cpu cortex-a7 bash -c 'curl "https://raw.githubusercontent.com/Crilum/Github-Actions-App-Builds/main/antimicrox_build.sh" | bash'
      - uses: actions/upload-artifact@v2
        with:
          name: antimicrox_${webVer}_armhf.deb
          path: $GITHUB_WORKSPACE/antimicrox_${webVer}_armhf.deb

          
