name: Build apps

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  AntiMicroX:
    # The type of runner that the job will run on
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:

      - name: Setup
        run: |
          sudo apt install qemu-user curl bash
          get_release() {
          curl --silent "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name' | sed s/v//g
          }
          validate_url(){
          if command wget -q --spider "$1"; then
          return 0
          else
          return 1
          fi
          }
          echo "Checking URLs..."
          validate_url "https://api.github.com/repos/AntiMicroX/antimicrox/releases/latest"
          if [ "$?" == "1" ]; then
          echo "Got a bad response from 'https://api.github.com/repos/AntiMicroX/antimicrox/releases/latest'"
          exit 1
          else
          validate_url "https://github.com/AntiMicroX/antimicrox"
          if [ "$?" == "1" ]; then
          echo "Got a bad response from 'https://github.com/AntiMicroX/antimicrox'"
          exit 1
          fi
          fi
          echo "Done."
          webVer=$(get_release AntiMicroX/antimicrox)
          echo "VERSION=$webVer" >> $GITHUB_ENV
          echo "BASE_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Run build script
        run: sudo qemu-arm -cpu cortex-a7 /usr/bin/bash -c 'curl "https://raw.githubusercontent.com/Crilum/Github-Actions-App-Builds/main/antimicrox_build.sh" | bash'#curl -q "https://raw.githubusercontent.com/Crilum/Github-Actions-App-Builds/main/antimicrox_build.sh" | bash
      - uses: actions/upload-artifact@v2
        with:
          name: antimicrox_${{ env.VERSION }}_armhf.deb
          path: ${{ env.BASE_DIR }}/antimicrox/antimicrox_${{ env.VERSION }}_armhf.deb

          
