name: Build

on:
  push:
    branches: 
      - 'main'
    paths: 
      - 'latest_release'
  workflow_dispatch:

jobs:
  Build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          echo "REL=$(cat latest_release)" >> $GITHUB_ENV
      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:arm64-focal
        with:
          args: >
            bash -c
            "apt update && DEBIAN_FRONTEND=noninteractive apt install -y libqt5widgets5 git doxygen g++ cmake extra-cmake-modules qt5-default qttools5-dev qttools5-dev-tools libsdl2-dev libxi-dev libxtst-dev libx11-dev itstool gettext &&
            git clone https://github.com/AntiMicroX/antimicrox &&
            cd antimicrox &&
            mkdir build && cd build &&
            cmake --build . --target package;
            ls"
            
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "antimicrox/build/*"
          body: "# test"
          name: test-antimicrox
          tag: test-antimicrox

  Build-armhf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          echo "REL=$(cat latest_release)" >> $GITHUB_ENV
      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:armhf-focal
        with:
          args: >
            bash -c
            "apt update && DEBIAN_FRONTEND=noninteractive apt install -y libqt5widgets5 git doxygen g++ cmake extra-cmake-modules qt5-default qttools5-dev qttools5-dev-tools libsdl2-dev libxi-dev libxtst-dev libx11-dev itstool gettext &&
            git clone https://github.com/AntiMicroX/antimicrox &&
            cd antimicrox &&
            mkdir build && cd build &&
            QT_SELECT=5 cmake .. -DCPACK_GENERATOR="DEB" && 
            QT_SELECT=5 cmake --build . --target package;
            ls"
            
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "antimicrox/build/*"
          body: "test-antimicrox"
          name: test-antimicrox
          tag: vtest-antimicrox
